anitafrancuart/urls.py
from django.conf.urls import include, url, handler404, handler500, handler403, handler400, re_path
from blog import views
from gallery.views import *
from blog.feeds import LatestPostsFeed

from django.urls import path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework_nested import routers
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

import djoser
from djoser.urls import authtoken

### Admin ###

admin.site.site_header = 'Anita Francu Art Admin Panel'
admin.site.site_title = 'Anita Francu Art'

### Router Implemenation ###

router = routers.SimpleRouter()
router.register(r'gallery', AlbumListView)
router.register(r'images', AlbumImageListView, basename='images')
router.register(r'users', UsersView, basename='users')
router.register(r'groups', GroupsView, basename='groups')

albums_router = routers.NestedSimpleRouter(router, r'gallery', lookup='gallery')
albums_router.register(r'images', AlbumImageView, basename='gallery-image')

### Error Handling ###
handler404 = PageView.handler404

sitemaps = {
    'post': PostSitemap,
}

urlpatterns = [
    path('', PageView.home_page, name='home'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
	
    path('register', PageView.register_page, name='register_page'),
    path('login', PageView.login_page, name='login_page'),
    path('logout', PageView.logout_page, name='logout_page'),	
	path('about', PageView.about_page, name='about_page'),
	path('contact', PageView.contactView, name='contactView'),
	path('success', PageView.successView, name="successView"),
    path('contribution/', PageView.donation_page, name="donation_page"),
	
	url(r'^search/', AfaSearchView.as_view(), name="search_page"),

    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include(albums_router.urls)),
    url(r'^api/v1/auth/', include(djoser.urls.authtoken)),
    url(r'^admin/', admin.site.urls, name='admin_page'),
	#url(r'^static/(?P<path>.*)$', serve), re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    #url(r'^media/(?P<path>.*)$', serve), re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),	
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
	#url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

blog/urls.py
from . import views
from .feeds import LatestPostsFeed

from django.urls import path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),

    # showing post by tags
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<slug:post>/', views.post_detail, name='post_detail'),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from sorl.thumbnail import ImageField

from django.db.models import Q

# Create your models here.

class ArticleManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(body__icontains=query)|
                         Q(slug__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct()
        return qs.filter(status='published')

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset() \
            .filter(status='published')

class Post(models.Model):
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    post_image = models.ImageField(upload_to='media', blank=True)	
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='created')

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    #objects = models.Manager()
    objects = ArticleManager()        
    published = PublishedManager()  # Our custom manager.

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.created.year,
                             self.created.month,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=40)
    email = models.EmailField()
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class' : 'share-form-name', 'placeholder': 'Type your message', 'style':'background-color: #ffffffa8'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'share-form-email', 'placeholder': 'Enter your email', 'style':'background-color: #ffffffa8'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'share-form-to', 'placeholder': 'Send to email', 'style':'background-color: #ffffffa8'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'class' : 'share-form-comm', 'placeholder': 'Type your message', 'rows': 5, 'style':'background-color: #ffffffa8'}))

class CommentForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'comment-name-form', 'placeholder': 'Enter your name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'comment-form-email', 'placeholder': 'Enter your email address', 'style':'background-color: #ffffffa8'}))	
    comment = forms.CharField(widget=forms.Textarea(attrs={'class' : 'comment-form', 'placeholder': 'Type your comment', 'rows': 5, 'style':'background-color: #ffffffa8'}))	
    class Meta:
        model = Comment
        fields = ['name', 'email', 'comment']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib import messages

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             created__year=year,
                             created__month=month)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        # Check is the form is valid
        if comment_form.is_valid():
            # create the comment but don't save it to the db just yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to db now
            new_comment.save()
            messages.success(request, "You're comment has been submitted successfully. Thank you!")
            return HttpResponseRedirect(request.path)
#            return render(request, 'blog/post/detail.html', {
#                          'post': post,
#                          'comments': comments,
#                          'new_comment': new_comment,
#                          'comment_form': comment_form,
#                        })
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})

def post_share(request, post_id):
    # retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form fields pass validation
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommend you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'valeriu.hudea@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


# searching against multiple fields with SearchVector
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

           # Ordinary full-text search
            results = Post.published.annotate(
                search=SearchVector('title', 'body'),
            ).filter(search=query)

            # full-text search with stemming and ranking functionality
            #search_vector = SearchVector('title', weight='A') + \
            #                SearchVector('body', weight='B')
            #search_query = SearchQuery(query)
            #results = Post.published.annotate(
            #    search=search_vector,
            #    rank=SearchRank(search_vector, search_query)
            #).filter(rank__gte=0.3).order_by('-rank')

            # Search beased on Triagram Similarity
            # results = Post.published.annotate(
            #     similarity=TrigramSimilarity('title', query),
            # ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

anitafrancuart/templates/blog/post/detail.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<div class="body-container text-center" style="padding-top: 20px;">
	<div class="container text-center">
		<div class="col-xl contact-block">
				<div class="jumbotron vertical-center" style="text-align: left">
						  <div class="section-title">
							<h2 style="font-family: Poppins, sans-serif; color: #D0D0D0;text-align:left">Blog Post</h2>
							<p style="text-align:left">{{ post.title }}</p>
						  </div>
						{% if messages %}
						  {% for message in messages %}
							 <h2{% if message.tags %} class="" {% endif %}>{{ message }}</h2>
						  {% endfor %}
						{% endif %}
						<!-- Author -->
						<p class="lead" style="color: #007cff">
							by
							<a href="#" style="color: #888">{{ post.author }}</a>
						</p>

						<hr>

						<!-- Date/Time -->
						<p style="color: #fff">Posted on {{ post.publish }}</p>

						<hr>

						<!-- Preview Image -->
						{% if post.post_image %}
						<img class="img-fluid rounded" src="{{ post.post_image.url }}" alt="post image" width="900" height="300">
                        {% else %}
						
					    <img class="img-fluid rounded" src="" alt="post image" width="900" height="300">
						
						{% endif %}
						<hr>

						<!-- Post Content -->
						<p class="blog-body-text">{{ post.body }}</p>

						<hr>
						<p>
							<a href="{% url "blog:post_share" post.id %}">
								Share this Post
							</a>
						</p>
						<hr>
						<h2 style="font-weight: 700">Similar posts</h2>
						{% for post in similar_posts %}
							<p>
								<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
							</p>
						{% empty %}
							There are no similar posts yet.
						{% endfor %}
						{% with comments.count as total_comments %}
							<h2 style="font-weight: 700">
								{{ total_comments }} comment{{ total_comments|pluralize }}
							</h2>
						{% endwith %}
						{% for comment in comments %}
							<div class="comment" style="word-break: break-all">
								<p class="info">
									Comment {{ forloop.counter }} by {{ comment.name }}
									{{ comment.created }}
								</p>
                                
								{{ comment.comment|linebreaks }}

								<div><h2 style="color: #05dcff">______ </h2></div>
							</div>
						{% empty %}
							<p>There are no comments yet.</p>
						{% endfor %}

						<!--{% if new_comment %}
							<h2>Your comment has been added.</h2>
						{% else %}-->
							<!-- Comments Form -->
							<div class="card my-4 info-box" style="background-color: rgba(255, 255, 255, 0.08)">
								<p style="font-family: Poppins, sans-serif;font-size: 36px;text-align: left;padding-left: 4px">Leave a Comment <i class="fa fa-comment"></i></p>
								<div class="card-body">
									<form method="post" style="display: grid">
										<div class="form-group">
											{{ comment_form.as_p }}
											{% csrf_token %}
										</div>
								    <div style="position: relative;text-align: center !important;">
									 <button class="btn-ho effect01" type="submit" style="padding-left: 4px;padding-right: 4px;">Add Comment</button>		
									</div>
									</form>
								</div>
							</div>
						{% endif %}
			    </div>
	    </div>
    </div>
</div>	
{% endblock %}

{% block widgets %}
{% include "widgets.html" %}
{% endblock %}

anitafrancuart/templates/blog/post/latest_posts.html
{% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
{% endfor %}

anitafrancuart/templates/blog/post/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% load thumbnail %}

{% block title %}Anita Francu's Art Blog{% endblock %}
{% block content %}
    <!-- Page Content -->
<div class="body-container text-center">
   <div class="container text-center" style="padding-top: 20px;">
    <div class="col-xl blog">
	 <div class="jumbotron vertical-center">
	  <div class="section-title">
		<h2 style="font-family: Poppins, sans-serif; color: #D0D0D0;text-align:left">Blog</h2>
		<p style="text-align:left">My Art Blog</p>
	  </div>
    <!-- Blog Post -->
    {% if tag %}
        <h2 style="font-family: Poppins, sans-serif; color: #D0D0D0;text-align:left">Posts tagged with "<em>{{ tag.name }}</em>"</h2>
    {% endif %}
    {% for post in posts %}
        <div class="card mb-4" id="cardib">
		    {% thumbnail post.post_image "600x600" as img %}
			<img src="{{ img.url }}" alt="Card image cap">
            <!--img class="card-img-top" src="{{ img.url }}" alt="Card image cap" width="750" height="600"-->
            {% endthumbnail %}
            <div class="card-body">
                <h2>
                    <a href="{{ post.get_absolute_url }}">
                        <h2 class="card-title">{{ post.title }}</h2>
                    </a>
                    <p class="tags" style="font-size: 16px; color: #012988;">
                        Tags:
                        {% for tag in post.tags.all %}
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                                {{ tag.name }}
                            </a>
                            {% if not forloop.last %},
                            {% endif %}
                        {% endfor %}

                    </p>
                </h2>

                {#        {{ post.body|truncatewords:30|linebreaks }}#}
                <p class="blog-body-text">{{ post.body|truncatewords_html:30 }}
                </p>
                <a href="{{ post.get_absolute_url }}" class=""><button class="btn-ho effect01">Read &rarr;</button></a>
            </div>
            <div class="card-footer text-muted">
                Published {{ post.publish }} by <strong>{{ post.author }}</strong>
            </div>
        </div>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
	  </div>
	 </div>
	</div>
</div>	
{% endblock %}

{% block widgets %}
{% include "widgets.html" %}
{% endblock %}

anitafrancuart/templates/blog/post/search.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>There are no results for your query</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <!-- Search Widget -->
        <div class="card my-4">
            <h5 class="card-header">Search for posts</h5>
            <div class="card-body">
                <div class="input-group">
                    <form class="form-group" method="get">
                        {{ form.as_p }}
                        <span class="input-group-btn">
							<input class="btn btn-primary" type="submit" value="Search">
						</span>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

anitafrancuart/templates/blog/post/share.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="body-container text-center gallery-main-div" style="padding-top: 20px;">
   <div class="container text-center">
    <div class="col-xl">
     <div class="jumbotron vertical-center" style="padding: 3px;">	  
	  
			<section id="portfolio" class="portfolio">
				<div class="container" style="height: auto">

				  <div class="section-title" style="padding-top: 30px;">
					<h2>Share</h2>
					<p>Blog Post Share</p>
				  </div>
				{% if sent %}
					<h1>E-mail sent successfully</h1>
					<p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}</p>
				{% else %}
					<h1>Share "{{ post.title }}" by e-mail</h1>
					<form method="post" style="display: grid;">
						{{ form.as_p }}
						{% csrf_token %}

					<div class="form-actions">
						<button class="btn-ho effect01" type="submit" style="margin-left: -75%;margin-top: 2px">Share &#9993;</button>
					</div
					</form>
				{% endif %}
                </div>
            </section>
		</div>
	 </div>
	</div>
</div>			
{% endblock %}