anitafrancuart/urls.py
from django.conf.urls import include, url, handler404, handler500, handler403, handler400, re_path
from blog import views
from gallery.views import *
from blog.feeds import LatestPostsFeed

from django.urls import path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework_nested import routers
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

import djoser
from djoser.urls import authtoken

### Admin ###

admin.site.site_header = 'Anita Francu Art Admin Panel'
admin.site.site_title = 'Anita Francu Art'

### Router Implemenation ###

router = routers.SimpleRouter()
router.register(r'gallery', AlbumListView)
router.register(r'images', AlbumImageListView, basename='images')
router.register(r'users', UsersView, basename='users')
router.register(r'groups', GroupsView, basename='groups')

albums_router = routers.NestedSimpleRouter(router, r'gallery', lookup='gallery')
albums_router.register(r'images', AlbumImageView, basename='gallery-image')

### Error Handling ###
handler404 = PageView.handler404

sitemaps = {
    'post': PostSitemap,
}

urlpatterns = [
    path('', PageView.home_page, name='home'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
	
    path('register', PageView.register_page, name='register_page'),
    path('login', PageView.login_page, name='login_page'),
    path('logout', PageView.logout_page, name='logout_page'),	
	path('about', PageView.about_page, name='about_page'),
	path('contact', PageView.contactView, name='contactView'),
	path('success', PageView.successView, name="successView"),
    path('contribution/', PageView.donation_page, name="donation_page"),
	
	url(r'^search/', AfaSearchView.as_view(), name="search_page"),

    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^blog/', include('blog.urls', namespace='blog')),

    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include(albums_router.urls)),
    url(r'^api/v1/auth/', include(djoser.urls.authtoken)),
    url(r'^admin/', admin.site.urls, name='admin_page'),
	#url(r'^static/(?P<path>.*)$', serve), re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    #url(r'^media/(?P<path>.*)$', serve), re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),	
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
	#url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

blog/urls.py
from . import views
from .feeds import LatestPostsFeed

from django.urls import path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),

    # showing post by tags
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<slug:post>/', views.post_detail, name='post_detail'),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

gallery/urls.py
from django.urls import path
from .feeds import LatestGalleryFeed
from django.conf.urls import include, url, re_path

from .views import *

app_name = 'gallery'

### URL Output regex ###

urlpatterns = [
	#path('404', PageView.handler404, {'exception': Exception()}),

	path('', gallery_page, name='gallery_page'),
	path('tag/<slug:tag_slug>/', gallery_page, name='gallery_page_by_tag'),
    path('<slug:album>/', gallery_detail, name='gallery_detail'),
    path('<slug:album>/tag/<slug:tag_slug>/', gallery_detail, name='gallery_detail_by_tag'),
    path('<slug:album>/', gallery_detail, name='gallery_detail'),
    path('<slug:image_slug>/artworkdetails', artwork_details, name='artwork_details'),
] 

gallery/views.py
from __future__ import unicode_literals
from itertools import chain

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import admin, messages
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound, HttpRequest
from django.views.generic import DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail, BadHeaderError
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import ListView
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib import messages

from taggit.models import Tag
from django.db.models import Count, Q

from rest_framework import status, viewsets, generics, permissions, renderers
from rest_framework.decorators import action, api_view
from rest_framework.response import Response
from rest_framework.parsers import JSONParser

#from .models import *
from .serializers import *
from .forms import *

from gallery.models import Album, AlbumImage
from blog.models import Post

def gallery_page(request, tag_slug=None):
    object_list = Album.visible.all()
    tags = object_list.order_by('tags__name').values_list('tags__name', flat=True).distinct()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])		
    paginator = Paginator(object_list, 4)
    page = request.GET.get('page')
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1) # If page is not an integer, deliver first page.
    except EmptyPage:
        albums = paginator.page(paginator.num_pages) # If page is out of range (e.g.  9999), deliver last page of results.
    return render(request, 'gallery/gallery.html', {'albums': albums, 'tag': tag, 'tags': tags})

def gallery_detail(request, album):
    album = get_object_or_404(Album, slug=album,
                             visibility='visible')

    images = AlbumImage.objects.filter(album=album.id)
	
    # List of similar albums
    post_tags_ids = album.tags.values_list('id', flat=True)
    similar_albums = Album.visible.filter(tags__in=post_tags_ids) \
        .exclude(id=album.id)
    similar_albums = similar_albums.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-created')[:4]
    return render(request, 'gallery/album_detail.html', {'album': album, 'images': images, 'similar_albums': similar_albums})

def artwork_details(request, image_slug):

    album_image = get_object_or_404(AlbumImage, slug=image_slug)

    return render(request, 'gallery/artwork-details.html', {'album_image': album_image})

class AfaSearchView(ListView):
    template_name = 'gallery/search_page.html'
    paginate_by = 10
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)
        albums = Album.visible.all()
        blogs = Post.published.all()
        queryset_chain = chain(albums, blogs)		
        quertyset_list = sorted(queryset_chain, key=lambda instance: instance.pk, reverse=True)
		
        if query is not None:
            #painting_results = AlbumImage.objects.search(query)
            album_results = Album.objects.search(query)
            blog_results = Post.objects.search(query)
            queryset_chain = chain(album_results, blog_results)
            quertyset_list = sorted(queryset_chain, key=lambda instance: instance.pk, reverse=True)            
            self.count = len(quertyset_list)
            return quertyset_list	
        return Album.objects.none() and Post.objects.none()

class PageView():

    def home_page(request):
        object_list = Album.visible.all()
        return render(request, 'gallery/home.html')

    def donation_page(request):
        object_list = Album.visible.all()
        return render(request, 'gallery/donation_page.html')
		
    def handler404(request, exception):
        assert isinstance(request, HttpRequest)
        return render(request, 'handler404.html', None, None, 404)
			
    def about_page(request):

        return render(request, 'gallery/about.html')		

    def contact_page(request):

        return render(request, 'gallery/contact.html')		

    def contactView(request):
        if request.method == 'GET':
            form = ContactForm()
        else:
            form = ContactForm(request.POST)
            to_email_list = ['valzld@protonmail.com', 'valeriu.hudea@gmail.com']
            if form.is_valid():
                form.save()			    
                name = form.cleaned_data['name']
                subject = form.cleaned_data['subject']
                from_email = form.cleaned_data['email']
                contact_message = form.cleaned_data['message']
                message = "Name: " +name + " |" + " Sender's Email: " +from_email + " |" + " Message: " +contact_message
                try:
                    send_mail(subject, message, from_email, to_email_list)
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                return redirect('successView')
        return render(request, "gallery/contact.html", {'form': form})

    def successView(request):
        return render(request, 'gallery/success.html')
	
    def delete_all_user_orders(username):
        Storage.objects.filter(owner=username).filter(already_ordered=False).delete()
        return True

    def calculate_total_price(username):
        total_prices = ''
        for obj in Storage.objects.filter(added_by=username).filter(already_ordered=False):
            price_all += obj.price
        return total_price

    def register_page(request):
        if not request.user.is_authenticated:
            if request.method == "POST":
                form = RegistrationForm(request.POST)
                if form.is_valid():
                    form.save()
                    username = form.cleaned_data["username"]
                    password = form.cleaned_data["password1"]
                    user = authenticate(username=username, password=password)
                    login(request, user)
                    return redirect("home")
                else:
                    return render(request, 'registration/register.html', {'form': form})
            else:
                form = RegistrationForm()
            context = {"form": form}
            return render(request, 'registration/register.html', context)
        else:
            return redirect("home")

    def login_page(request):
        if not request.user.is_authenticated:
            if request.method == "POST":
                form = UserLoginForm(data=request.POST)
                if form.is_valid():
                    username = form.cleaned_data["username"]
                    password = form.cleaned_data["password"]
                    user = authenticate(username=username, password=password)
                    if user is not None:
                        login(request, user)
                        if next is not None:
                            return redirect("home")
                        else:
                            return redirect("home")
            else:
                form = UserLoginForm()
            context = {"form": form}
            return render(request, 'registration/login.html', context)
        else:
            return redirect("home")

    def logout_page(request):
        if request.user.is_authenticated:
            logout(request)
        return redirect("home")

    #@login_required

    #@staff_member_required

### Api Views ###

class UsersView(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `GET` and `POST` actions for Users.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer

class GroupsView(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `GET` and `POST` actions for Groups.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

######################################

class AlbumImageView(viewsets.ModelViewSet):
    serializer_class = AlbumImageSerializer

    def get_queryset(self):
        return AlbumImage.objects.filter(album=self.kwargs['pk'])

class AlbumListView(viewsets.ModelViewSet):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer

    def perform_create(self, serializer):
        serializer.save

class AlbumView(viewsets.ModelViewSet):
    #lookup_field = 'id'
    #permission_classes = [IsOwner]
    serializer_class = AlbumSerializer
    queryset = Album.objects.all()

class AlbumImageListView(viewsets.ModelViewSet):
    queryset = AlbumImage.objects.all()
    serializer_class = AlbumImageSerializer

class AlbumImageView(viewsets.ModelViewSet):
    queryset = AlbumImage.objects.all()
    serializer_class = AlbumImageSerializer

anitafrancuart/templates/gallery/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="body-container text-center">
    <div class="container text-center">
    <div class="col-xl aboutme">
      <div class="jumbotron vertical-center">

		  <div class="section-title">
			<h2>About</h2>
			<p>Who I am and what I'm about</p>
		  </div>

		  <div class="row">
			<div class="col-lg-6">
			  <img src="{% static "anitafrancuart/assets/img/me.jpg" %}" class="img-fluid" alt="">
			</div>
			<div class="col-lg-6 pt-4 pt-lg-0 content" data-aos="fade-left">
			  <h3 style="font-family: Raleway, sans-serif;text-align: left;color: #3e77ff">Artist &amp; Designer</h3>
			  <p class="font-italic" style="text-align:left;color: #fff">
				 “Art evokes the mystery without which the world would not exist.” 
			  </p>
			  <div class="row">
				<div class="col-lg-11">
				  <ul class="about-me-l" style="padding-left: 5px">
					<li style="color: #fff"><i class="fa fa-chevron-right" style="color: #3e77ff"></i> <strong>Birthday:</strong> 3 Mar 1991</li>
					<li style="color: #fff"><i class="fa fa-chevron-right" style="color: #3e77ff"></i> <strong>City:</strong> Brasov, Romania</li>
					<li style="color: #fff"><i class="fa fa-chevron-right" style="color: #3e77ff"></i> <strong>Age:</strong> 29</li>
					<li style="color: #fff"><i class="fa fa-chevron-right" style="color: #3e77ff"></i> <strong>Freelance:</strong> Available</li>
				  </ul>
				</div>
			  </div>
			</div>
			  <p style="text-align:left; color: #fff;margin-left: 10px;margin-top: 10px">
			   Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis. Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus itaque neque.
			  </p>		
		  </div>
		  
		<div class="counts container">

		  <div class="row" style="padding-top: 20px;">

			<div class="col-lg-3 col-md-6">
			  <div class="count-box">
				<i class=""><span style="color: #fff" data-toggle="counter-up">243</span>
				</i>
				<p style="color: #3e77ff; font-size: 20px;"><strong>Art Work</strong></p>
				
			  </div>
			</div>

			<div class="col-lg-4 col-md-6 mt-5 mt-md-0">
			  <div class="count-box">
				<i class=""><span style="color: #fff" data-toggle="counter-up">131</span></i>				
				<p style="color: #3e77ff; font-size: 20px;"><strong>Projects</strong></p>
			  </div>
			</div>

		  </div>

		</div>

    </div>

<!-- End Counts -->

  <!--/section--><!-- End About Section -->
        </div>
    </div>
</div>	
{% endblock %}

{% block widgets %}
{% include "widgets.html" %}
{% endblock %}

anitafrancuart/templates/gallery/album_detail.html
{% extends "base.html" %}

{% load static %}

{% load thumbnail %}
{% load blog_tags %}
{% load gallery_tags %}

{% block title %}{{ album.title }}{% endblock %}

{% block content %}
<div class="body-container text-center gallery-main-div" style="padding-top: 20px;">
   <div class="container text-center">
    <div class="col-xl">
     <div class="jumbotron vertical-center" style="padding: 3px;">

	<section id="portfolio" class="portfolio">
		<div class="container">
		
			  <div class="section-title">
				<h2 style="font-family: Poppins, sans-serif; color: #D0D0D0;text-align:left">Portofolio Album</h2>
				<p style="text-align:left">{{ album.title }}</p>
			  </div>

			  <!-- Date/Time -->
			  <p style="color: #fff; text-align: left">Published on {{ album.created }}</p>

			  <hr>
			  <!-- Album Preview Image -->
			  <div style="display: inline-flex;">
			  {% if album.thumbnail %}
			  
				  {% thumbnail album.thumbnail "x280" as albmimg %}
				  <img class="img-fluid-gal-thumb" src="{{ albmimg.url }}" alt="{{ album.title }}">
				  {% endthumbnail %}

				  {% else %}
				  <img src="" class="img-fluid-gal" alt="{{ album.title }}">
		      {% endif %}
			  
			  <hr>
			  
			  <!-- Album Description -->
			  <div class="ablum-desc" style="text-align: left; padding: 15px; margin: 0; font-size: 28px;">
			  {% if album.description %}
			  <h4 style="color: #8ae4ff; font-family: Oleo Script;">Details: </h4>
			  <p class="album_p_desc">{{ album.description }}</p>
			  {% else %}
			  <h4 style="color: #8ae4ff; font-family: Oleo Script;">No details available</h4>
			  {% endif %}
			  <!--p style="font-family: Poppins, sans-serif;font-style: italic; color: #1ab1ec;">Description: </p-->
			  <!--p style="margin: 0">{{ album.description|markdown }}</p-->
			  </div>
 			 </div>
			  
			  <hr>
					
			  <!-- Portofolio Containing Image list start -->
              {% if images %}
			  <div class="row portfolio-container" style="background-color: #19294873; padding-top: 20px; padding-bottom: 0;border-radius: 10px">
			  {% for image in images %}
				<div class="col-lg-6 col-md-6 portfolio-item filter-abstract">
				  <div class="portfolio-wrap">
				    {% thumbnail image.image "x400" as img %}
					<img src="{{ img.url }}" class="img-fluid-gal" alt="">
                    {% endthumbnail %}					
					<div class="portfolio-info">
					  <h4>{{ image.name }}</h4>
					  <div class="portfolio-links">				   
						<a href="{{ image.get_absolute_image_url }}" data-gall="portfolioGallery" class="venobox zld-mobico" title="{{ image.name}}"><i class="fa fa-search-plus zld-mob-i"></i></a>
						{% if image.availability == 'available' or image.availability == 'sold' %}
						<a href="{% url 'gallery:artwork_details' image.slug %}" data-gall="portfolioDetailsGallery" data-vbtype="iframe" class="venobox" title="{{ image.name }} Details"><i class="fa fa-info-circle zld-mob-i"></i></a>
						{% else %}
						<div></div>
						{% endif %}
					  </div>
					</div>
				  </div>
				</div>
			  {% endfor %}	
			  </div> <!-- Portofolio Image List -->			  
			  
			  {% else %}
				<p style="color: #2e76ff; font-size: 24px;"> No Image Uploaded to this ablum yet!</p>
              {% endif %}
			  
				<hr>						
				
				<h2 style="font-weight: 700">Similar Albums</h2>
				{% for album in similar_albums %}
					<p>
						<a href="{{ album.get_absolute_url }}">{{ album.title }}</a>
					</p>
				{% empty %}
					There are no similar albums yet.
				{% endfor %}
	   </div><!-- End Container -->
	</section><!-- End Section --> 
       
	 </div><!-- End Jumbotron -->
	</div><!-- End Col-xl -->
   </div><!-- End Container-text-center -->
</div><!-- End Body Content -->   
{% endblock %}

anitafrancuart/templates/gallery/artwork-details.html
{% load static %}

{% load gallery_tags %}

{% load thumbnail %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Anita Francu Art | Artwork Details</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@600&display=swap" rel="stylesheet"> 
  <!-- Vendor CSS Files -->
  <link href="{% static 'anitafrancuart/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static "anitafrancuart/assets/css/vhud-artwork-sell.css" %}">
 
</head>

<body class="artwork-sell-body">

  <main id="main">

    <!-- ======= Artwork Details ======= -->
    <div id="artwork-details" class="portfolio-details">
      <div class="container">

        <div class="row">

          <div class="col-lg-8">
            <h2 class="portfolio-title">Artwork Profile</h2>
			{% if album_image %}
            <div class="owl-carousel portfolio-details-carousel">
		    {% thumbnail album_image.image "460x500" as img %}
			<img src="{{ img.url }}" class="img-fluid" alt="{{ album_image.alt }}">
            {% endthumbnail %}
            </div>
			{% endif %}
          </div>

          <div class="col-lg-4 portfolio-info">
            <h3>Painting information</h3>
            <ul class="sell-i-details">
              <li><strong>Name:</strong> {{ album_image.name }}</li>
              <li><strong>Artist:</strong> Anita Fraâcu</li>
              <li><strong>Status:</strong> {{ album_image.availability }}</li>
              <li><strong>Listing date:</strong> {{ album_image.created }}</li>
			  <li><strong style="color: #85e3ff;">Price:</strong> <strong style="color: #fff;">{% if album_image.price > 0 %} {{ album_image.price }} € {% else %} not available {% endif %}</strong></li>
			  <li><strong style="color: #66d3f4;">If interested:</strong> <a class="sell-contact-a" href="{% url 'contactView' %}" target="_top">Contact me</a></li>
            </ul>

			<div class="artwork-item-description">
			{% if album_image.description %}
			<h4>Description: </h4>
			<p class="album_p_desc">{{ album_image.description }}</p>
			{% else %}
			<h4>No description available</h4>
			{% endif %}
			</div>
          </div>

        </div>

      </div>
    </div><!-- End Portfolio Details -->

  </main><!-- End #main -->

  <div class="bottom-bar">
    Powered by <a class="vhud-brand" href="#">vhud</a>
  </div>

</body>

</html>

anitafrancuart/templates/gallery/footer.html
{% load i18n %}
<footer class="py-4 footer-style">
  <div class="container">
  {% block footer %}
	<div class="row">
		<div class="col-md-10 col-lg-8 mx-auto">

            <ul class="list-inline text-center social-icons">
			  <li><a class="instagram" href="https://www.instagram.com/anitafrancu333/" target="_blank"><i class="fa fa-instagram" aria-hidden="true" style="font-size: 24px;"></i></a></li>
              <li><a class="facebook" href="https://www.facebook.com/AnitaFrancu333" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a class="mailto" href="mailto:valeriu.hudea@gmail.com" target="_blank"><i class="fa fa-envelope"></i></a></li>   
            </ul>
			<p class="m-0 text-center text-dark">Copyright &copy;<a href="/" class="copyright-name"><strong> Anita Francu</strong></a> 2020. All Rights Reserved.
			</p>
		</div>

	  <!--div class="col-md-4 col-sm-6 col-xs-12">
		<ul class="social-icons">
		  <li><a class="facebook" href="#"><i class="fab fa-facebook-f"></i></a></li>
		  <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
		  <li><a class="instagram" href="#"><i class="fab fa-instagram"></i></a></li>
		  <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>   
		</ul>
	  </div-->
	</div>
  </div>
  {% endblock %}
</footer>

anitafrancuart/templates/gallery/gallery.html
{% extends "base.html" %}

{% load static %}
{% load gallery_tags %}
{% load thumbnail %}
{% load active_link_tags %}

{% block title %}Anita Francu's Art Gallery{% endblock %}

{% block content %}
<div class="body-container text-center gallery-main-div" style="padding-top: 20px;">
   <div class="container text-center">
    <div class="col-xl">
     <div class="jumbotron vertical-center" style="padding: 3px;">	  
	  
			<section id="portfolio" class="portfolio">
				<div class="container gallery-container">

				  <div class="section-title" style="padding-top: 30px;">
					<h2>Portfolio</h2>
					<p>My Art &amp; Designs</p>
				  </div>

				  <div class="row">
					<div class="col-lg-12 d-flex justify-content-center">
					  <ul id="portfolio-flters">
					    <a href="{% url "gallery:gallery_page" %}"><li data-filter="*" class="{% if request.path == '/gallery/' %}activated{% endif %}">All</li></a>
							{% for tag in tags %}
								<a href="{% url "gallery:gallery_page_by_tag" tag %}"><li data-filter=".filter" class="{% if tag in request.path %}activated{% endif %}">{{ tag }}</li></a>
								{% empty %}
									no other tags
							{% endfor %}							
					  </ul>
					</div>
				  </div>
				  
				{% if tag %}
					<h2 style="font-family: Poppins, sans-serif; color: #D0D0D0;text-align:left">Albums tagged with "<em>{{ tag.name }}</em>"</h2>
				{% endif %}
				

				{% for album in albums %}
			    <div class="albums-list">
					   <a class="album_a_title" href="{{ album.get_absolute_url }}" title="{{ album.title }}"><h2 style="font-family: Allura, cursive; font-size: 48px;font-weight: 300">{{ album.title }}</h2></a>
						<p class="tags" style="font-size: 16px; color: #8b9295;">	
						    Tags:
							{% for tag in album.tags.all %}							     
								<a href="{% url "gallery:gallery_page_by_tag" tag.slug %}">{{ tag.name }}</a>
								{% if not forloop.last %},
								{% endif %}
							{% empty %}
							    no tags available
							{% endfor %}
						</p>
				  {% if album.thumbnail %}
			     <div class="portfolio-wrap" style="display: flex;justify-content: left;">
					{% thumbnail album.thumbnail "x300" as img %}
					<img src="{{ img.url }}" class="img-fluid-gallery" alt="{{ album.title }}">
					{% endthumbnail %}
					{% else %}
					<img src="" alt="{{ album.title }}" class="img-fluid-gallery" />
					{% endif %}
				   <a href="{{ album.get_absolute_url }}" title="{{ album.title }}">					
					<div class="portfolio-info">
					  <h4 class="album-wrap-view" style="">View Album</h4>		  
					  <div class="portfolio-links">

					  </div>
					</div>
				   </a>
				  
				  <div class="col-lg-6 col-md-2 portfolio-item" style="padding-top: 8%;padding-left:auto; padding-right: auto;">
				        {% if album.description %}
                        <h4 style="color: #8ae4ff; font-family: Oleo Script;">Details: </h4>
						<p class="album_p_desc" style="margin-right: 10%; margin-left:2%">{{ album.description }}</p>
						{% else %}
						<h4 style="color: #8ae4ff; font-family: Oleo Script;">No details</h4>
						{% endif %}
				  </div><!-- Album description -->
                 </div>
			   </div>
			   
			   <hr>
			   
			{% endfor %}
			
			{% include "pagination.html" with page=albums %}
			  </div>
			
		  </section>

        </div> <!--jumbotron-->
    </div> <!--col-xl-gallery-->
 </div> <!--container text-center-->
</div><!-- body-container -->

{% endblock %}

anitafrancuart/templates/gallery/latest_albums.html
{% for album in latest_albums %}
    <li>
        <a href="{{ album.get_absolute_url }}">{{ album.title }}</a>
    </li>
{% endfor %}